all:
	# g++ -O2 -c model.cpp
	# g++ -Wall -O2 -c main.cc -lGLU -lglut -lGL
	# g++ -Wall -o main main.o model.o -lGLU -lglut -lGL
	g++ -Wall -O2 -c main.cc -lGLU -lglut -lGL
	g++ -Wall -o main main.o -lGLU -lglut -lGL
	./main
  
clean:
	rm *.o